dependencies:
- name: postgresql
  version: 10.4.8
  repository: https://marketplace.azurecr.io/helm/v1/repo
  condition: postgresql.enabled
- name: ingress-nginx
  version: 3.31.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx.enabled